/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital;

import Hospital.SecretarySystem.SecretaryPage;
import Hospital.DoctorSystem.DoctorPage;
import Hospital.AdminSystem.AdminPage;
import Hospital.PatientSystem.PatientPage;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Luke
 */
public class LoginPage extends javax.swing.JFrame {
//private static Scanner x;
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserIDTextbox = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        PasswordTextbox = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Hospital management system login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("User ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password");

        UserIDTextbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UserIDTextbox.setToolTipText("");

        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        PasswordTextbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LoginButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(PasswordTextbox))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(UserIDTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserIDTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(LoginButton)
                .addGap(0, 65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
      //String userID = UserIDTextbox.getText();
      //String password = PasswordTextbox.getText();
        try {
            //Logins(); 
            Logins2();
        } catch (Exception ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
      //if(userID.equals("a") && password.equals("a")){
          //AdminPage obj = new AdminPage();
          //obj.setVisible(true);
          //dispose();
      //} else if(userID.equals("p") && password.equals("p")){
          //PatientPage obj = new PatientPage();
          //obj.setVisible(true);
          //dispose();
      //}else if(userID.equals("d") && password.equals("d")){
          //DoctorPage obj = new DoctorPage();
          //obj.setVisible(true);
          //dispose();
      //}else if(userID.equals("s") && password.equals("s")){
          //SecretaryPage obj = new SecretaryPage();
          //obj.setVisible(true);
          //dispose();
      //}
      //else{
      //JOptionPane.showMessageDialog(rootPane, "User ID or password is incorrect");
      //}
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }
    public void Logins()throws Exception 
  { 
  // We need to provide file path as the parameter: 
  // double backquote is to avoid compiler interpret words 
  // like \test as \t (ie. as a escape sequence) 
  File file = new File("Logins.txt"); 
  
  BufferedReader br = new BufferedReader(new FileReader(file)); 
  
  String st; 
  String userID = UserIDTextbox.getText();
  String password = PasswordTextbox.getText();
  String login = userID + password;
  Boolean log = false;
  while ((st = br.readLine()) != null){ 
      if(st.equals(login)){
          char ch1 = st.charAt(0);
          log = true;
          String s=String.valueOf(ch1);
          if(s.equals("A")){
          AdminPage obj = new AdminPage();
          obj.setVisible(true);
          dispose();
          }else if(s.equals("S")){
          SecretaryPage obj = new SecretaryPage();
          obj.setVisible(true);
          dispose();
          }else if(s.equals("D")){
          DoctorPage obj = new DoctorPage();
          obj.setVisible(true);
          dispose();
          }else if(s.equals("P")){
          PatientPage obj = new PatientPage();
          obj.setVisible(true);
          dispose();
          }
      }   
  }
  if(log==false){
  JOptionPane.showMessageDialog(rootPane, "User ID or password is incorrect");
  }
  } 
 public void Logins2() throws Exception
 {
   boolean found = false;
   String userID = "";
   String password = "";
   String name = "";
   String address = "";
   String sex = "";
   String age = "";
 
   try {
            File f = new File("Users.txt");
            Scanner sc = new Scanner(f);

            List<Person> people = new ArrayList<Person>();

            while(sc.hasNextLine() && !found){
                String line = sc.nextLine();
                String[] details = line.split(":");
                userID = details[0];
                password = details[1];
                name = details[2];
                address = details[3];
                sex = details[4];
                age = details[5];
                Person p = new Person(userID,password,name,address,sex,age);
                people.add(p);
                if(userID.equals(UserIDTextbox.getText())&& password.equals(PasswordTextbox.getText()))
                {
                    char first = userID.charAt(0);
                    String first1 = Character.toString(first);
                if(first1.equals("a") || first1.equals("A")){
                AdminPage obj = new AdminPage();
                obj.setVisible(true);
                dispose();
                } else if(first1.equals("p") || first1.equals("P")){
                PatientPage obj = new PatientPage();
                obj.setVisible(true);
                dispose();
                }else if(first1.equals("d") || first1.equals("D")){
                DoctorPage obj = new DoctorPage();
                obj.setVisible(true);
                dispose();
                }else if(first1.equals("s") || first1.equals("S")){
                SecretaryPage obj = new SecretaryPage();
                obj.setVisible(true);
                dispose();
                }}
            }
            sc.close();
            for(Person p: people){
                System.out.println(p.toString());
            }

        } catch (FileNotFoundException e) {         
            e.printStackTrace();
        }
    }
  //if(userID.trim().equals(UserIDTextbox.getText()) && password.trim().equals(PasswordTextbox.getText()))
  //{
      //System.out.println("yes");
  //}
  
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordTextbox;
    private javax.swing.JTextField UserIDTextbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
